# Generated by Django 5.1.2 on 2024-11-29 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transctions', '0002_chart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
